name: build against latest Ubuntu
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install libncursesw5-dev
    - name: cmake build
      run: cmake -Bbuild .
    - name: cmake make
      run: cmake --build build/
